alert("Esto es una ventana emergente")
console.log("Se agrega segunda versión desde local")
console.log("se agrega cambio en rama pruebas")
console.log("segundos cambios en rama pruebas")
console.log ("Aquí iria el código")
